### ISSUE TITLE
kernel4f121f3247

### ISSUE THREAD

**Issue by konakanv** [souravs17031999/Retinal_blindness_detection_Pytorch#11]
the folder kernel4f121f3247 is not available. How can i get it.

**Comment by souravs17031999** [comment]
This is a auto generated folder on kaggle when you upload datasets (here I uploaded model as dataset on kaggle as a workaround since you can't directly upload models).
You will not need this for the initial training, this is only required if you are using pretrained model or any other artifacts uploaded on kaggle while doing inference like I have initially trained model and uploaded it a place. Then, I am loading the saved model to train it further therefore, that folder only contains the pretrained model which was saved earlier.

Please re-open if any other issue.
